### ISSUE TITLE
Tracking issue for num-complex 0.3

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-complex#70]
- [x] Update MSRV to 1.31, needed to deal with rand's use of package renaming
  - [x] #71: Convert to 2018 edition too
- ~~#35: Consider implementing operators by reference with `NumRef` etc.~~
  - Postponed.
- [x] #50: Consider implementing assign-operators with internal assign-ops too.
- [x] #65: Update to rand 0.7 (MSRV 1.32)

Other PRs and issues may be included too, but these are the ones that impact compatibility.
